version: 2

sources:
  - name: covid_data
    description: 'Indonasia Covid data'
    database: FIVETRAN_INTERVIEW_DB
    schema: GOOGLE_SHEETS
    tables:
      - name: COVID_19_INDONESIA_ASWIN_RAJARAM
        description: 'Details about Covid in Indonasia'
    

